FROM openjdk:8

ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASS
ARG HOST=localhost
ARG ART_NAME

ENV DB_HOST ${DB_HOST}
ENV DB_PORT ${DB_PORT}
ENV DB_NAME ${DB_NAME}
ENV DB_USER ${DB_USER}
ENV DB_PASS ${DB_PASS}
ENV HOST ${HOST}

EXPOSE 9000
WORKDIR /opt/samsara
COPY ${ART_NAME} .
CMD java -jar *.jar